services:
  luigi-scheduler:
    build:
      context: .
      target: app
    container_name: bees-luigi-scheduler
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8082:8082"
    command: luigid --address 0.0.0.0 --port 8082
  spark-app:
    build:
      context: .
      target: app
    container_name: bees-spark-app
    depends_on:
      - luigi-scheduler
    volumes:
      - ./:/app
    working_dir: /app
    command: luigi --module app.orchestration.luigi_pipeline BreweryMedallionPipeline --scheduler-host luigi-scheduler --scheduler-port 8082
  streamlit-app:
    profiles:
      - optional
    build:
      context: .
      target: streamlit
    container_name: bees-streamlit-app
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8501:8501"
    command: streamlit run app/ui/streamlit_app.py --server.address 0.0.0.0 --server.port 8501
